ACON-iOS/ACON-iOS/Presentation/SpotList/View/SpotListViewController.swift, ACON-iOS/ACON-iOS/Presentation/SpotListFilter/View/SpotListFilterViewController.swift
- #3 
**<문제>**
segment 이동을 하면 viewModel.soptType이 즉각적으로 업데이트됨
그러나 viewModel.soptType 초기값은 nil이기 때문에 
segment 이동을 안 하고 conduct 버튼을 누를 경우 restaurant가 아닌 nil이 post 됨
**<해결>**
conduct 버튼을 누르면 restaurant로 설정되도록 수정
```
conductButton 눌렀을 때,
viewModel.spotType.value == nil일 경우 
viewModel.spotType.value = restaurant로 설정
```
- Resolved: #3
=> [FIX] 세그먼트 이동 안 하고 conduct할 시 restaurant로 post 안 하는 문제 해결 (#3)

ACON-iOS/ACON-iOS.xcodeproj/project.pbxproj, ACON-iOS/ACON-iOS/Global/UIComponents/CustomAlert/AlertHandler.swift, ACON-iOS/ACON-iOS/Global/UIComponents/CustomAlert/Type/AlertType.swift, ACON-iOS/ACON-iOS/Network/Auth/AuthService.swift, ACON-iOS/ACON-iOS/Network/Auth/AuthTargetType.swift, ACON-iOS/ACON-iOS/Network/Auth/DTO/PostLogoutRequest.swift, ACON-iOS/ACON-iOS/Presentation/Profile/View/ProfileSettingViewController.swift, ACON-iOS/ACON-iOS/Presentation/Profile/ViewModel/SettingViewModel.swift
- #35 
- 로그아웃 로직과 API를 연결했습니다.
- 로그아웃 시 UserDefaults 전체 삭제, Splash로 이동
https://github.com/user-attachments/assets/50f59575-dcb0-4e05-b56c-058f23698ef8
- Resolved: #35
=> [FEAT] 로그아웃 로직 및 API 연결 (#35)

ACON-iOS/ACON-iOS.xcodeproj/project.pbxproj, ACON-iOS/ACON-iOS/Network/Profile/DTO/GetNicknameValidityRequestQuery.swift, ACON-iOS/ACON-iOS/Network/Profile/ProfileService.swift, ACON-iOS/ACON-iOS/Network/Profile/ProfileTargetType.swift, ACON-iOS/ACON-iOS/Presentation/Profile/View/ProfileEditViewController.swift, ACON-iOS/ACON-iOS/Presentation/Profile/ViewModel/ProfileViewModel.swift
- #49 
닉네임 유효성 검증 API를 연결했습니다.
서버에서 1. 중복 확인, 2. 유효성(입력마스크)를 확인하는데, 
1번 중복 확인은 메시지 띄우는 거 연결했고
2번 에러코드를 받았을 경우는 Todo만 추가했습니다
그리고 검증 중일 때 동글동글 로띠 돌아가는 거 추가 예정입니다
https://github.com/user-attachments/assets/652d53ae-7976-49e5-b60c-89b61f1bedd8
- Resolved: #49
=> [FEAT] 닉네임 유효성 검증 API 연결 (#49)

ACON-iOS/ACON-iOS.xcodeproj/project.pbxproj, ACON-iOS/ACON-iOS/Global/Utils/Enums/HeaderType.swift, ACON-iOS/ACON-iOS/Global/Utils/Enums/ImageType.swift, ACON-iOS/ACON-iOS/Network/Base/ACService.swift, ACON-iOS/ACON-iOS/Network/Image/DTO/GetPresignedURLRequest.swift, ACON-iOS/ACON-iOS/Network/Image/DTO/GetPresignedURLResponse.swift, ACON-iOS/ACON-iOS/Network/Image/DTO/PutImageToPresignedURLRequest.swift, ACON-iOS/ACON-iOS/Network/Image/ImageService.swift, ACON-iOS/ACON-iOS/Network/Image/ImageTargetType.swift, ACON-iOS/ACON-iOS/Presentation/Album/Model/AlbumModel.swift, ACON-iOS/ACON-iOS/Presentation/Album/View/PhotoSelectionViewController.swift, ACON-iOS/ACON-iOS/Presentation/Album/ViewModel/AlbumViewModel.swift, ACON-iOS/ACON-iOS/Presentation/Profile/Model/ProfileModel.swift, ACON-iOS/ACON-iOS/Presentation/Profile/View/ProfileEditViewController.swift, ACON-iOS/ACON-iOS/Presentation/Profile/ViewModel/ProfileViewModel.swift
- #45
PresignedURL 획득 API와, 획득한 PresignedURL에 사진 업로드하는 서버통신 구현했습니다.
프로필 수정 API 바인딩과 관련해서 들어가야 하는 곳은 🧇로 표시해놨으니 확인해주세용 @yurim830 
- Resolved: #45
=> [FEAT] PresignedURL 획득 API 연결 (#45)

ACON-iOS/ACON-iOS.xcodeproj/project.pbxproj, ACON-iOS/ACON-iOS/Network/Profile/DTO/PatchProfileRequest.swift, ACON-iOS/ACON-iOS/Network/Profile/ProfileService.swift, ACON-iOS/ACON-iOS/Network/Profile/ProfileTargetType.swift, ACON-iOS/ACON-iOS/Presentation/Profile/View/ProfileEditViewController.swift, ACON-iOS/ACON-iOS/Presentation/Profile/ViewModel/ProfileViewModel.swift
- #56
프로필 수정 API를 연결했습니다.
2차 스프린트 API 끝 !!
- Resolved: #56
=> [FEAT] 프로필 수정 API 연결 (#56)

ACON-iOS/ACON-iOS.xcodeproj/project.pbxproj, ACON-iOS/ACON-iOS/Application/AppDelegate.swift, ACON-iOS/ACON-iOS/Global/Extensions/UIViewController+.swift, ACON-iOS/ACON-iOS/Global/UIComponents/DummyComponent.swift, ACON-iOS/ACON-iOS/Global/UIComponents/LoginModal/View/LoginModalViewController.swift, ACON-iOS/ACON-iOS/Presentation/Album/View/PhotoCollectionViewController.swift, ACON-iOS/ACON-iOS/Presentation/Album/ViewModel/AlbumViewModel.swift, ACON-iOS/ACON-iOS/Presentation/LocalVerification/View/LocalMapViewController.swift, ACON-iOS/ACON-iOS/Presentation/LocalVerification/View/LocalVerificationViewController.swift, ACON-iOS/ACON-iOS/Presentation/LocalVerification/View/VerifiedAreasEditViewController.swift, ACON-iOS/ACON-iOS/Presentation/Profile/View/ProfileEditViewController.swift, ACON-iOS/ACON-iOS/Presentation/Profile/View/ProfileSettingViewController.swift, ACON-iOS/ACON-iOS/Presentation/Profile/View/ProfileView.swift, ACON-iOS/ACON-iOS/Presentation/Profile/View/ProfileViewController.swift, ACON-iOS/ACON-iOS/Presentation/SpotDetail/View/SpotDetailViewController.swift, ACON-iOS/ACON-iOS/Presentation/SpotDetail/ViewModel/SpotDetailViewModel.swift, ACON-iOS/ACON-iOS/Presentation/Upload/View/DropAcornViewController.swift, ACON-iOS/ACON-iOS/Presentation/Upload/View/ReviewFinishedViewController.swift, ACON-iOS/ACON-iOS/Presentation/Upload/View/SpotSearchViewController.swift, ACON-iOS/ACON-iOS/Presentation/Upload/ViewModel/SpotReviewViewModel.swift
- #62
1차 QA 전 에러 핸들링, 게스트 분기처리, 각종 에러 & 노란 경고 해결 및 코드 정돈을 간단하게 진행했습니다.
이 PR을 기점으로 1.0(6) 테플 배포될 예정입니다.
- Resolved: #62
=> [CHORE] Sprint 2 1차 QA 준비 (#62)

ACON-iOS/ACON-iOS/Presentation/Withdrawal/View/CustomTextFieldView.swift
- #70 
\n 다중 입력시 레이아웃 깨지며, 강제종료 현상 -> scrollView 대체
https://github.com/user-attachments/assets/d13dc71d-9760-414d-b57d-903eeefa9cd1
- Resolved: #70
=> [FIX] CustomTextFieldview layout problem (#70)

ACON-iOS/ACON-iOS/Presentation/Withdrawal/View/Cell/WithdrawalTableViewCell.swift, ACON-iOS/ACON-iOS/Presentation/Withdrawal/View/CustomTextFieldView.swift, ACON-iOS/ACON-iOS/Presentation/Withdrawal/View/WithdrawalTableView.swift, ACON-iOS/ACON-iOS/Presentation/Withdrawal/View/WithdrawalViewController.swift, ACON-iOS/ACON-iOS/Presentation/Withdrawal/ViewModel/WithdrawalViewModel.swift
- #83 
1. \n 못넣게하기
2. 테이블뷰 셀 선택시 버튼만 눌렀을 때 셀 선택되게 하기
https://github.com/user-attachments/assets/c3546874-b751-48ac-ba42-b4487af3b233
- Resolved: #83
=> [FIX] 2차 QA Withdrawal (#83)

ACON-iOS/ACON-iOS/Presentation/Base/BaseErrorView.swift, ACON-iOS/ACON-iOS/Presentation/SpotList/Type/SpotListErrorType.swift, ACON-iOS/ACON-iOS/Presentation/SpotList/View/SpotListView.swift, ACON-iOS/ACON-iOS/Presentation/SpotList/View/SpotListViewController.swift, ACON-iOS/ACON-iOS/Presentation/SpotList/ViewModel/SpotListViewModel.swift
- #81 
- skeleton이 적어도 0.5초 이상 뜨도록 설정
- 에러뷰 계층 수정 (SpotList를 덮는 문제 해결)
- 에러뷰에 새로고침 버튼 추가
- 장소리스트 있을 때도 잘 나오는지는 곧 테스트계정으로 시험해보겠습니다
|서비스 불가지역|장소 없을 때|
|:--:|:--:|
|<img src = "https://github.com/user-attachments/assets/f5a93e41-0846-4128-80f3-1b61d4db3568" width ="250">|<img src = "https://github.com/user-attachments/assets/c4bbac24-54fe-485a-98d5-139437d4a254" width ="250">|
- Resolved: #81
=> [FIX] 2차 QA 대응 (SpotList 에러뷰) - 유림 (#81)

ACON-iOS/ACON-iOS/Network/SpotList/DTO/PostSpotListRequest.swift, ACON-iOS/ACON-iOS/Presentation/Base/BaseErrorView.swift, ACON-iOS/ACON-iOS/Presentation/SpotList/View/SpotListViewController.swift, ACON-iOS/ACON-iOS/Presentation/SpotListFilter/Model/SpotListFilterModel.swift, ACON-iOS/ACON-iOS/Presentation/SpotListFilter/Type/SpotType.swift
- #88 
추천장소리스트API 이동거리, 가격필드 옵셔널로 변경
- Resolved: #88
=> [FIX] SpotList DTO 변경사항 반영 (#88)

ACON-iOS/ACON-iOS.xcodeproj/project.pbxproj, ACON-iOS/ACON-iOS/Global/Utils/ACLocationManager.swift, ACON-iOS/ACON-iOS/Network/Auth/DTO/PostLoginResponse.swift, ACON-iOS/ACON-iOS/Presentation/Login/ViewModel/LoginViewModel.swift, ACON-iOS/ACON-iOS/Presentation/SpotDetail/View/SpotDetailViewController.swift, ACON-iOS/ACON-iOS/Presentation/SpotList/View/SpotListView.swift, ACON-iOS/ACON-iOS/Presentation/SpotList/View/SpotListViewController.swift
- #86
3차 QA 준비 및 반영한 뒤, 마지막 QA 확인했습니다.
- Resolved: #86
=> [CHORE] 3차 QA 준비 및 반영 (#86)

ACON-iOS/ACON-iOS.xcodeproj/project.pbxproj, ACON-iOS/ACON-iOS/Global/Literals/AmplitudeLiterals.swift
- #92
엠플리튜드 event name의 효율적 처리를 위한 AmplitudeLiterals를 구현했습니다.
`AmplitudeLiterals.eventname.{event_name}`으로 불러주세요 !
- Resolved: #92
=> [FEAT] AmplitudeLiterals 구현 (#92)

ACON-iOS/ACON-iOS/Presentation/SpotList/View/SpotListViewController.swift, ACON-iOS/ACON-iOS/Presentation/SpotListFilter/View/SpotListFilterViewController.swift
- #93 
제 몫의 앰플을 붙였습니다
- 필터 버튼 눌렀을 때
- 필터 적용 버튼 눌렀을 때
- 장소 리스트 중 하나 눌렀을 때 (인덱스별로 구분)
| 앰플 스크린샷 |
|:--:|
|<img width="300" alt="image" src="https://github.com/user-attachments/assets/9c936aa1-681d-4361-b9c8-dde16b92600d" /> |
|<img width="400" alt="image" src="https://github.com/user-attachments/assets/7cd2f6bf-7ce7-43ee-b39f-cb976db4d9c8" />|
|<img width="250" alt="image" src="https://github.com/user-attachments/assets/535f0c75-d259-4e2d-9d80-07626d104cf4" /> <img width="250" alt="image" src="https://github.com/user-attachments/assets/9c2eba21-86c4-480c-9e22-591c4ad47a56" />|
- Resolved: #93
=> [FEAT] 앰플리튜드 붙이기 - 유림 (#93)

ACON-iOS/ACON-iOS/Global/Extensions/UIViewController+.swift, ACON-iOS/ACON-iOS/Global/Literals/AmplitudeLiterals.swift, ACON-iOS/ACON-iOS/Global/Service/AmplitudeManager.swift, ACON-iOS/ACON-iOS/Global/UIComponents/LoginModal/View/LoginModalViewController.swift, ACON-iOS/ACON-iOS/Presentation/LocalVerification/View/LocalMapViewController.swift, ACON-iOS/ACON-iOS/Presentation/LocalVerification/View/LocalVerificationFinishedViewController.swift, ACON-iOS/ACON-iOS/Presentation/LocalVerification/View/LocalVerificationViewController.swift, ACON-iOS/ACON-iOS/Presentation/Login/View/LoginViewController.swift, ACON-iOS/ACON-iOS/Presentation/Login/ViewModel/LoginViewModel.swift, ACON-iOS/ACON-iOS/Presentation/OnBoarding/View/OnboardingViewController.swift, ACON-iOS/ACON-iOS/Presentation/Profile/View/ProfileSettingViewController.swift, ACON-iOS/ACON-iOS/Presentation/Profile/View/ProfileViewController.swift, ACON-iOS/ACON-iOS/Presentation/Profile/ViewModel/SettingViewModel.swift, ACON-iOS/ACON-iOS/Presentation/SpotDetail/View/SpotDetailViewController.swift, ACON-iOS/ACON-iOS/Presentation/SpotList/View/SpotListViewController.swift, ACON-iOS/ACON-iOS/Presentation/TabBar/ACTabBarController.swift, ACON-iOS/ACON-iOS/Presentation/Upload/View/DropAcornViewController.swift, ACON-iOS/ACON-iOS/Presentation/Upload/View/SpotUploadViewController.swift, ACON-iOS/ACON-iOS/Presentation/Withdrawal/View/WithdrawalConfirmationViewController.swift, ACON-iOS/ACON-iOS/Presentation/Withdrawal/View/WithdrawalViewController.swift
- #90
제 몫의 엠플리튜드를 연결했습니다.
아직 확인을 못 해서, 집 가서 확인하고 머지할게요 !
|기능|스크린샷|기능|스크린샷|기능|스크린샷|
|:--:|:--:|:--:|:--:|:--:|:--:|
|아이폰 16 Pro|<img src = "" width ="250">|아이폰 13 mini|<img src = "" width ="250">|아이폰 se|<img src = "" width ="250">|
- Resolved: #90
=> [FEAT] 엠플리튜드 붙이기 - 수민 (#90)

ACON-iOS/ACON-iOS.xcodeproj/project.pbxproj, ACON-iOS/ACON-iOS/Application/SceneDelegate.swift, ACON-iOS/ACON-iOS/Global/Extensions/UIViewController+.swift, ACON-iOS/ACON-iOS/Global/Service/AppVersionManager.swift, ACON-iOS/ACON-iOS/Global/Settings/Info.plist, ACON-iOS/ACON-iOS/Presentation/Profile/View/Cell/SettingTableViewCell.swift, ACON-iOS/ACON-iOS/Presentation/Profile/View/ProfileSettingViewController.swift, ACON-iOS/ACON-iOS/Presentation/Profile/ViewModel/SettingViewModel.swift
- #99
v1.0.1 업데이트를 진행했습니다.
- 업데이트 알림 기능 추가
- localization 한국 추가
- 설정 - 버전 정보 로직 구현
- 외국에서는 업데이트 알림이 항상 떠서 1.0.2에서 고칠 예정입니다. (버전을 한국 URL에서 가져와서 그런 것 같음)
- 앱스토어 언어를 영어에서 한국어로 변경하기 위해 한국 로컬을 추가했는데, 변경이 안 돼서 다시 제대로 알아보고 1.0.2에서 적용하겠습니다!
- Resolved: #99
=> [RELEASE] v1.0.1 업데이트 (#99)

ACON-iOS/ACON-iOS/Presentation/Profile/View/Cell/SettingTableViewCell.swift, ACON-iOS/ACON-iOS/Presentation/Profile/View/Component/LabelBoxWithDeletableButton.swift, ACON-iOS/ACON-iOS/Presentation/Profile/View/Component/ProfileBoxComponent.swift, ACON-iOS/ACON-iOS/Presentation/Profile/View/Component/ProfileEditValidMessageView.swift, ACON-iOS/ACON-iOS/Presentation/Profile/View/Component/ProfileImageEditButton.swift, ACON-iOS/ACON-iOS/Presentation/Profile/View/ProfileEditView.swift, ACON-iOS/ACON-iOS/Presentation/Profile/View/ProfileEditViewController.swift, ACON-iOS/ACON-iOS/Presentation/Profile/View/ProfileSettingViewController.swift, ACON-iOS/ACON-iOS/Presentation/Profile/View/ProfileView.swift, ACON-iOS/ACON-iOS/Presentation/Profile/View/ProfileViewController.swift, ACON-iOS/ACON-iOS/Presentation/Profile/ViewModel/ProfileViewModel.swift, ACON-iOS/ACON-iOS/Presentation/Profile/ViewModel/SettingViewModel.swift
- #104
- class, 프로퍼티 접근제어자 설정
- 공백 제거
- MARK 주석 통일
- Resolved: #104
=> [CHORE] 프로필 관련 코드 정리 - 접근제어자, 주석 등 (#104)

.gitignore, ACON-iOS/ACON-iOS.xcodeproj/project.pbxproj, ACON-iOS/ACON-iOS/Application/AppDelegate.swift
- #101 
Firebase Crashlytics을 적용하였습니다.
GoogleService-Info.plist 파일이 필요한데, 슬랙에 보내드릴게요 !! 
이 파일은 Config처럼 깃에 올리면 안 돼서, .gitignore에 넣어놨지만 혹시 모르니 커밋하지 말아주세요
사진처럼 다음과 같이 넣어주세요!
슬랙봇이랑 연동이 됐는데, 이상하게 비정상 종료 에러메시지가 안 오네요.. 🥹
연동 부분은 웹사이트에서 설정하는 거라 더 알아보겠습니다.
- Resolved: #101
=> [SETTING] Firebase Crashlytics 적용 (#101)

ACON-iOS/ACON-iOS/Presentation/Profile/View/ProfileEditView.swift, ACON-iOS/ACON-iOS/Presentation/Profile/View/ProfileEditViewController.swift, ACON-iOS/ACON-iOS/Presentation/SpotList/View/SpotListViewController.swift
- #179 
- **홈**
- 비로그인 상태에서 길찾기 버튼 클릭 시 로그인 모달 Present
- **프로필 편집**
- 첫 진입 시 저장 버튼 비활성화, 백버튼 Alert 생략
- 바깥 영역 터치 시 keyboard dismiss
- 닉네임 대문자 입력 시 소문자로 자동 변환
- 닉네임 placeholder 제거
https://github.com/user-attachments/assets/bec03007-a84e-41b1-a155-b8a9a7d79808
- Resolved: #179
=> [CHORE] 홈, 프로필 편집 QA 반영 (#179)

ACON-iOS/ACON-iOS/Presentation/SpotList/View/Cell/SpotListGoogleAdCollectionViewCell.swift, ACON-iOS/ACON-iOS/Presentation/SpotList/View/Component/SpotListCollectionViewFlowLayout.swift, ACON-iOS/ACON-iOS/Presentation/SpotList/View/SpotListViewController.swift
- #217 
- 광고 삽입 인덱스 수정: 장소 5 -> 광고 1 -> 장소 5 -> 광고1
- 광고가 떴는데 skeleton 이 보이는 문제가 있어, Cell configure 시 skeleton hide 추가
- Cell prepareForReuse 부분에 hideSkeleton 이 있을 이유가 없어서 삭제
- Resolved: #217
=> [FIX] 광고 삽입 인덱스 수정, 광고 configure 시 스켈레톤 숨기기 (#217)

ACON-iOS/ACON-iOS.xcodeproj/project.pbxproj, ACON-iOS/ACON-iOS/Global/Settings/Info.plist, ACON-iOS/fastlane/Fastfile, README.md
- #221
2.0.0 릴리즈
심사 1시간컷 뭐지
- Resolved: #221
=> [RELEASE] v2.0.0 업데이트 (#221)
